### ISSUE TITLE
I think we still can not change the server Port and bundle the js locally right?

### ISSUE THREAD

**Issue by WillCoder** [race604/ZhiHuDaily-React-Native#1]
I think we still can not change the server Port and bundle the js locally right?

**Comment by race604** [comment]
I have add standalone APK support in this [commit](https://github.com/race604/ZhiHuDaily-React-Native/commit/007dd90f9fc57388200b356f22390c39ea7a3da4). If you can read Chinese, you can read this post:  http://www.race604.com/rn-android-standalone-apk/

**Comment by WillCoder** [comment]
cool
haha, I am a Chinese

**Comment by WillCoder** [comment]
I see, so you just copy the js file to asset to solve this issue currently, but I still think that it should be done by the framework just like iOS 'bundle' right?

**Comment by WillCoder** [comment]
do you have the wechat account? my wechat 13659258231
