### ISSUE TITLE
I launch app show this error

### ISSUE THREAD

**Issue by hnrainll** [race604/ZhiHuDaily-React-Native#10]
Starting the app (adb shell am start -n com.rctzhihudaily/.MainActivity)...
Starting: Intent { cmp=com.rctzhihudaily/.MainActivity }
Error type 3
Error: Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist.

**Comment by race604** [comment]
duplicated with #5

**Comment by hnrainll** [comment]
ths
