### ISSUE TITLE
react-native start的时候出错

### ISSUE THREAD

**Issue by jianfengye** [race604/ZhiHuDaily-React-Native#13]
git clone下来代码，进入root

```
➜  ZhiHuDaily-React-Native git:(master) npm install
➜  ZhiHuDaily-React-Native git:(master) react-native start
Command `start` unrecognized. Did you mean to run this inside a react-native project?
```

如何处理。。。

**Comment by race604** [comment]
你好，开发环境都配置好了吗？

**Comment by jianfengye** [comment]
开发环境都配置好了，我自己创建的AwsomeProject是可以运行起来的。

```
➜  AwesomeProject  react-native start
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/yejianfeng/Documents/baichebao/AwesomeProject


React packager ready.

[17:13:53] <START> Building Dependency Graph
[17:13:53] <START> Crawling File System
[17:13:54] <END>   Crawling File System (534ms)
[17:13:54] <START> Building in-memory fs for JavaScript
[17:13:55] <END>   Building in-memory fs for JavaScript (1135ms)
[17:13:55] <START> Building in-memory fs for Assets
[17:13:55] <END>   Building in-memory fs for Assets (591ms)
[17:13:55] <START> Building Haste Map
[17:13:56] <START> Building (deprecated) Asset Map
[17:13:56] <END>   Building (deprecated) Asset Map (308ms)
[17:13:56] <END>   Building Haste Map (822ms)
[17:13:56] <END>   Building Dependency Graph (3083ms)
```

**Comment by jianfengye** [comment]
但是使用awsomeProject和ZhihuDaily项目的时候有一个不通就是npm的源不同

在跑ZhihuDaily项目的时候，我用的是淘宝的npm

http://blog.csdn.net/spy19881201/article/details/26943051

不知道这个有没有影响？

**Comment by race604** [comment]
`react-native run-android` 呢？

**Comment by jianfengye** [comment]
```
➜  ZhiHuDaily-React-Native git:(master) ✗ react-native run-android
Command `run-android` unrecognized. Did you mean to run this inside a react-native project?
```

**Comment by race604** [comment]
This may help: https://github.com/facebook/react-native/issues/2880

**Comment by jianfengye** [comment]
真是。。。。看来是node_module的问题

**Comment by zzyyppqq** [comment]
![image](https://cloud.githubusercontent.com/assets/8832903/11555302/31232242-99da-11e5-8159-0182b3e170c9.png)

**Comment by zzyyppqq** [comment]
![image](https://cloud.githubusercontent.com/assets/8832903/11555350/8fca5432-99da-11e5-940c-18511a28fabd.png)
是这个原因吗

**Comment by jorry** [comment]
我也遇到这个问题，怎么解

**Comment by jiangqingbo** [comment]
运行 react-native run-android 之前先运行 npm install , 解决了这个问题。

**Comment by easternHong** [comment]
大神们,可以配置使用全局的node_modules吗,每一个工程目录下面都有一个node_modules文件夹,文件基本相同.

**Comment by chocoluffy** [comment]
@easternHong 配置全局通常是两种情况， 一个是给开发工具dev tool比如grunt, http-server, browser-sync等为的是开发的方便， 或者第二种接口的command line tool比如aws\react-native等等， 感觉大致上还是工具类的居多， 框架类的还是通过node_modules来安装更新， 毕竟npm install可以根据package.json规定的版本区间自动更新符合要求的版本号~个人感受哈， 欢迎补充!

**Comment by Wenqin-231** [comment]
npm installl
react-native start
react-native run-android
亲测可解决。

**Comment by wenqin-231** [comment]
npm installl
react-native start
react-native run-android

**Comment by PayneJay** [comment]
npm installl
react-native start
react-native run-android
这三步之后完美的运行起来了，赞👍

**Comment by shenshizhong** [comment]
ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jdk1.8.0_101\bin

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

这个错误怎么处理呢
