### ISSUE TITLE
模拟器里运行 也提示unbale to download to js bundle

### ISSUE THREAD

**Issue by changfuguo** [race604/ZhiHuDaily-React-Native#14]
hi  在设备上运行   unbale to download  js bundle 设置下adb reverse 好了

在模拟器里又出现这问题了，这个咋设置下呢？？

**Comment by changfuguo** [comment]
直接红通通一片，查了好多文档好像都没有说在设备里出现这个问题的

**Comment by race604** [comment]
出现这个问题，就是JS server没有连接上，还有就是看一下您的模拟器的 API level

**Comment by changfuguo** [comment]
我看了下 问题出在手机的dns设置上，，这里分两种情况
1  如果是用的emulator ，一般设置的dns默认是10.0.2.3，和当前的机器不在一个网段，需要手动设置下和当前dns为一个即可，步骤：

> adb shell 
> setprop net.dns1 '你的dns'

2 如果连的是机器，则需要你说的tcp reverse 将手机的8081端口转向当前pc的8081端口即可

我现在用的是模拟器，当时用手机连接时把`dns1`设置回默认的了，现在改成我的就好了，也就是说模拟器一样会出现 unbale to download js bundle，连不上JS server

坑啊 哈哈

**Comment by race604** [comment]
不错的经验，Great
