### ISSUE TITLE
请教如何设置点击回退回到上一级页面？

### ISSUE THREAD

**Issue by jianfengye** [race604/ZhiHuDaily-React-Native#15]
参考代码，我理解只要维护一个回退的堆栈就可以在点击back健的时候设置回到上个activity？

```
// 设置回退的堆栈
var _navigator;
BackAndroid.addEventListener('hardwareBackPress', function() {
    if (_navigator && _navigator.getCurrentRoutes().length > 1) {
        _navigator.pop();
        return true;
    }
    return false;
});

```

但是我设置了之后发现点击back都是退出app，@race604,能不能大致说下这种回退返回上一页是怎么做的？

**Comment by race604** [comment]
你理解是对的，但是要在 Activity 中加入这些代码：https://github.com/race604/ZhiHuDaily-React-Native/blob/master/android%2Fapp%2Fsrc%2Fmain%2Fjava%2Fcom%2Frace604%2Fzhihu%2Fdaily%2FMainActivity.java#L85-L91

**Comment by jianfengye** [comment]
谢谢，弄出来了
