### ISSUE TITLE
Debug in Chrome feature can not work in this project

### ISSUE THREAD

**Issue by laozhuang727** [race604/ZhiHuDaily-React-Native#16]
Hi,

This is a great "react native" demo for android. With the latest version, when I enable the "debug in chrome" option. The app stop in the Welcome page. And can not render the home page. 

It bring a big challenge for dev debugging.

Would you please help to take a look and provide a solution?

Thanks & Regards,
Ryan

**Comment by race604** [comment]
Debugging work perfect for me. Please check if you add some break points in the Chrome?

**Comment by laozhuang727** [comment]
Hi race,

Which react-native version are you using now? Is it 0.11.4? 

It seems in RCTZhiHuDaily, the setTimeOut function did not work. So the this.state.splashed==false. And it will keep render the SplashScreen, and can not update the Navigator component.

Thanks & Regards,
Ryan

**Comment by laozhuang727** [comment]
It is so Strange that, the TimerMixin setTimeout function is working fine in run model. But it is not trigger in debug model.

**Comment by laozhuang727** [comment]
I finally found the issue myself. The root cause is I was using genymotion as the mobile visual device. 
The timestamp setting in the visual device is different with current time (which is about 1 year different).

After change the timestamp in the visual device. The debug is working fine now.

Thanks a lot for your support!!

Regards,
Ryan

**Comment by race604** [comment]
Thank you Ryan. This is a great issue, I'll fix this bug when system time is not correct.

**Comment by race604** [comment]
All right, this seems is [JavaScript Runtime](http://facebook.github.io/react-native/docs/javascript-environment.html#content) problem, I'll close this issue.  Please make sure your device/emulator time is sync with your Computer when debugging.
