### ISSUE TITLE
Can not run in real device

### ISSUE THREAD

**Issue by carl1990** [race604/ZhiHuDaily-React-Native#18]
I clone this project and build.
intstall in real device but can not run well.

the error info is:
invariant violation: application has not registered.this either due to a require() error during initialization or failure call appRegistry.registerConponent.

and the click reload JS with error:
Unable to download JS bundle

how can resolve this problem

**Comment by misakuo** [comment]
clone this repository to your computer and unzip it.
then `cd ZhiHuDaily-React-Native`
run `npm install`
run `react-native start`
run `adb reverse tcp:8081 tcp:8081`
finally, click Reload JS and it's will be working

**Comment by uinz** [comment]
or shake your phone, settting your computer's IP,then reload js

**Comment by zanjs** [comment]
error: /Users/www/ios/ZhiHuDaily-React-Native/ios/main.jsbundle: No such file or directory
