### ISSUE TITLE
error: /Users/www/ios/ZhiHuDaily-React-Native/ios/main.jsbundle: No such file or directory

### ISSUE THREAD

**Issue by zanjs** [race604/ZhiHuDaily-React-Native#19]
error: /Users/www/ios/ZhiHuDaily-React-Native/ios/main.jsbundle: No such file or directory

**Comment by race604** [comment]
iOS is not support yet. I am working on it, the iOS version is coming soon.

**Comment by zanjs** [comment]
thanks,you are very good!

**Comment by race604** [comment]
Finish with this commit 
https://github.com/race604/ZhiHuDaily-React-Native/commit/18b325834a5c7c71a868cce4ffdddef47f3dc677
