### ISSUE TITLE
启动 app 的时候App 包下的 build.gradle 55行报错

### ISSUE THREAD

**Issue by tianshaokai** [race604/ZhiHuDaily-React-Native#2]
- What went wrong:
  Execution failed for task ':app:downloadJSBundle'.

不知道如何解决，希望你能给出解决问题的方法

**Comment by race604** [comment]
请确认已经打开了 JS Server，可以参考这篇博文：http://www.race604.com/rn-android-standalone-apk/

**Comment by tianshaokai** [comment]
哥们，可不可以加你qq 联系方式，多交流呢

**Comment by race604** [comment]
已加，close issue
