### ISSUE TITLE
Using your custom native modules

### ISSUE THREAD

**Issue by tolu360** [race604/ZhiHuDaily-React-Native#21]
Hello Jing,

Thank you for sharing your insights on creating android apps with RN. I'm impressed with your implementations of two custom native modules (webview & swiperefresh) that are not yet parts of the official release.

Please can I re-use these modules? Can they be re-used as-is? Thank you.

**Comment by race604** [comment]
I did not export these as standalone modules. So if you want use them, you can just copy this source file to your project.

**Comment by tolu360** [comment]
Thank you, I'd try to do just that.

**Comment by tolu360** [comment]
Thanks, I was able to make use of your RefreshLayout module.

Please, is it possible to use the Android Design Support Library modules such as the CollapsingToolbarLayout etc, in a react-native application like you did for the RefresherLayout? Can you show how in a sample app? Thanks

NB: I am not a native android developer.

**Comment by race604** [comment]
Sorry for reply so late.
Yes, you can do this. but I don't suggest to so. Because some modules (such as CoordinatorLayout and CollapsingToolbarLayout) depend on native touch response system, and can't be resued on iOS.
