### ISSUE TITLE
ListView的Android版本不支持sticky-header特性么？

### ISSUE THREAD

**Issue by misakuo** [race604/ZhiHuDaily-React-Native#23]
官方文档对`renderSectionHeader`函数的说明 "If provided, a sticky header is rendered for this section. The sticky behavior means that it will scroll with the content at the top of the section until it reaches the top of the screen, at which point it will stick to the top until it is pushed off the screen by the next section header." 但是我在您的project里看到renderSectionHeader之后header内容是被render出来了但是在滚动的时候header并没有被sticky住，是不是Android版本的ListView不支持这个特性？或是其他？

**Comment by race604** [comment]
Android 版本还不支持，https://github.com/facebook/react-native/issues/2700

**Comment by misakuo** [comment]
了解，十分感谢
