### ISSUE TITLE
linux编译android版本，运行时出错

### ISSUE THREAD

**Issue by awangbrace** [race604/ZhiHuDaily-React-Native#26]
你好：
       我这边在linux下搭建android的开发环境，按照官方的说明建立react native编译都其example都没有问题。在编译你这个客户端的代码时，没有错误信息。但是在运行时提示如下见附件。
        不知道有没有出现过类似问题？能否给个思路？多谢了。
![111](https://cloud.githubusercontent.com/assets/10293851/10564526/5db273d0-75ea-11e5-8b39-c36e961fc43c.png)

**Comment by race604** [comment]
这个应该是版本的问题。参考这里：https://github.com/facebook/react-native/issues/3344 您看一下 build.gradle 的依赖是不是对的： `compile 'com.facebook.react:react-native:0.12.+'`

**Comment by awangbrace** [comment]
build.gradle是对的。
更新了package.json中的版本号。但是问题依旧。还要继续尝试。谢谢了。

**Comment by race604** [comment]
Should be fix on latest version
