### ISSUE TITLE
如何开启悬浮窗设置

### ISSUE THREAD

**Issue by changfuguo** [race604/ZhiHuDaily-React-Native#3]
hi  我参考你的文章部署环境，在模拟器上打开也是一片红

有个问题请教下哈，怎么设置悬浮窗开启呢？？
我邮箱36977662@qq.com，求帮助下感谢~

**Comment by rainbo** [comment]
设置 》程序》知乎日报》权限》开启

**Comment by race604** [comment]
@rainbo 说的对
