### ISSUE TITLE
requiring unknown module “react-timer-mixin” 

### ISSUE THREAD

**Issue by lihemin** [race604/ZhiHuDaily-React-Native#30]
在windows 10下搭建的Android开发环境，运行报错。

**Comment by race604** [comment]
Windows 下我没有尝试过，您运行了 `npm install` 了么？有没有什么错误？

**Comment by lihemin** [comment]
npm install -g react-native-cli  安装这个了，可能是windows的原因吧 谢谢啦

**Comment by lihemin** [comment]
可能是windows的原因吧  谢谢啦

**Comment by race604** [comment]
不是安装 `react-native-cli`，是在代码根目录运行 `npm install`，请参考这里
https://github.com/race604/ZhiHuDaily-React-Native#how-to-run

**Comment by FaberSober** [comment]
Try this: npm i react-timer-mixin --save.
https://facebook.github.io/react-native/docs/timers.html#content
