### ISSUE TITLE
TypeError:expected dynamic type 'int64',but had type 'double'

### ISSUE THREAD

**Issue by coolegos** [race604/ZhiHuDaily-React-Native#33]
![image](https://cloud.githubusercontent.com/assets/6348861/10989041/452bc70c-847d-11e5-87ad-2e47741047d2.png)

可以进入到引导页面，但是打开就是这样了，自己搜索了，没有结局，不知道是什么问题

**Comment by shilu89757** [comment]
我也遇到这个问题了

**Comment by zhqchen** [comment]
npm install 的东西没下完吧。

**Comment by shilu89757** [comment]
不是，官方issue里边也说是版本的bug，但是不知道哪个版本是好用的

**Comment by race604** [comment]
The latest code will fix this
