### ISSUE TITLE
react-native run-android失败，找不到MainActivity

### ISSUE THREAD

**Issue by shilu89757** [race604/ZhiHuDaily-React-Native#38]
Starting the app (F:\Android\android-sdk/platform-tools/adb shell am start -n com.rctzhihudaily/.MainActivity)...
Starting: Intent { cmp=com.rctzhihudaily/.MainActivity }
Error type 3
Error: Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist.

**Comment by race604** [comment]
Please read closed issues first.
