### ISSUE TITLE
undefined is not an object (evaluating 'backandroid.addeventlistener')

### ISSUE THREAD

**Issue by chenlongkk** [race604/ZhiHuDaily-React-Native#4]
when i run your code，i got this error [undefined is not an object (evaluating 'backandroid.addeventlistener')],do you know how to solve this?

**Comment by tonylinyy** [comment]
+1

**Comment by race604** [comment]
Would you please past the full log? What's your node.js version?

**Comment by neekychan** [comment]
+1 lastest version

**Comment by wsxyeah** [comment]
![screen shot 2015-09-26 at 3 36 41 pm](https://cloud.githubusercontent.com/assets/3497889/10116344/62b85d64-6464-11e5-85e9-5172e6ed806b.png)

**Comment by fangleen** [comment]
+1, the same problem

**Comment by Acris** [comment]
+1

**Comment by race604** [comment]
You are using a wrong Node.js version, please use `$ node -v` to check version. Make sure using node 4.0.0 or newer.

**Comment by Acris** [comment]
@race604 Hi,I am use the latest version v4.1.1 and I have the  same problem, by the way, my OS is Ubuntu 15.04.

**Comment by fangleen** [comment]
I'm using the node 4.0.0 on Mac, the JS server has the following error:

Unable to resolve module regenerator/runtime.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/es6-extensions.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/done.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module regenerator/runtime.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/es6-extensions.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/done.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/core.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/core.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module stacktrace-parser/index.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module stacktrace-parser/lib/stacktrace-parser.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module rebound/rebound.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module immutable/dist/immutable.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module immutable/dist/immutable.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module AwesomeProject/index.android.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module rebound/rebound.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module immutable/dist/immutable.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module immutable/dist/immutable.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module stacktrace-parser/index.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module stacktrace-parser/lib/stacktrace-parser.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/core.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js
Unable to resolve module promise/setimmediate/core.js from /Users/test/Study/react/ZhiHuDaily-React-Native/android/app/build/intermediates/assets/debug/ReactNativeDevBundle.js

**Comment by race604** [comment]
@Acris please check this: https://github.com/facebook/react-native/issues/2968

**Comment by race604** [comment]
There is an known issue here:
https://github.com/facebook/react-native/issues/3080
It seems all android module broken when using react-native 0.11.2.
I'll use the newest version after that issue is resolved.

**Comment by fangleen** [comment]
yes, after change to 0.11.0, problem resolved. Thanks for your help! Nice job!

**Comment by race604** [comment]
The official team fixed the 0.11.2 problem, now we can use the newest version(0.11.3). Please remember run `npm udate` to upgrade the react-native.
