### ISSUE TITLE
Request: publish / open source AndroidSwipeRefreshLayout

### ISSUE THREAD

**Issue by jforaker** [race604/ZhiHuDaily-React-Native#40]
Seems like you guys have some pull to refresh mechanism built and working... I would love to see this published and open sourced, as there is nothing out there right now that works with Android

Thanks! 

```
      <AndroidSwipeRefreshLayout
        {...this.props}
        ref={RK_SWIPE_REF}
        style={styles.base}
        onRefresh={this._onRefresh}>
        {childrenWrapper}
      </AndroidSwipeRefreshLayout>
```

**Comment by szq4119** [comment]
+1

**Comment by race604** [comment]
`AndroidSwipeRefreshLayout` is not perfect, and this will be support officially.
