### ISSUE TITLE
Error: Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist.

### ISSUE THREAD

**Issue by jjskay** [race604/ZhiHuDaily-React-Native#43]
When I run the project of windows platform(Andriod) have a error: 
Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist. 
The project has being build successful .
I has been see #12, but i am will not Java and i am is a rookie with 'React Native'.
I hope download the project from git ,it run has not error. 
The error for a rookie is very difficult.
Thank you!

**Comment by Binaryify** [comment]
me too

**Comment by d668** [comment]
+1

**Comment by zhll912** [comment]
+1

**Comment by race604** [comment]
Fixed finally, c0b2e720133386aaeaac7fd1953f796851be930c
