### ISSUE TITLE
can you please fix the issue Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist.

### ISSUE THREAD

**Issue by d668** [race604/ZhiHuDaily-React-Native#45]
Starting: Intent { cmp=com.rctzhihudaily/.MainActivity }
Error type 3
Error: Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist.

**Comment by race604** [comment]
Fixed c0b2e720133386aaeaac7fd1953f796851be930c
