### ISSUE TITLE
为什么我使用xcode打开ios里面的xcodeproje

### ISSUE THREAD

**Issue by heeween** [race604/ZhiHuDaily-React-Native#49]
为什么我使用xcode打开ios里面的xcodeproj library里面一堆红色不存在文件 怎么解决呢
![image](https://cloud.githubusercontent.com/assets/12106605/11776179/138ca3f8-a280-11e5-99ef-1bddc573391b.png)

**Comment by race604** [comment]
Please run `npm install`
