### ISSUE TITLE
Error: Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist.

### ISSUE THREAD

**Issue by whmsysu** [race604/ZhiHuDaily-React-Native#5]
Try to run the project, but it says "Error type 3
Error: Activity class {com.rctzhihudaily/com.rctzhihudaily.MainActivity} does not exist.".Could anyone tell me how to fix this?

**Comment by yanqing1988** [comment]
同求大牛解决😄

**Comment by race604** [comment]
Because I change the default package name, you can just open this app by click the app icon in the launcher.

**Comment by d668** [comment]
wel this is an issue and you should't be closing it, you are using a standard framework, not your own, "open this app by click the app icon" is not a proper way, and also it contradicts your own instructions
