### ISSUE TITLE
Invariant Violation:Application RCTZhiHuDaily has not been registered

### ISSUE THREAD

**Issue by whmsysu** [race604/ZhiHuDaily-React-Native#8]
It shows this error message when I launch the app.Could anyone tell me how to fix that?

**Comment by race604** [comment]
Please check your development environment, refer this https://github.com/race604/ZhiHuDaily-React-Native#how-to-run

**Comment by whmsysu** [comment]
I already followed all the instructions list on the page. I can run other react-native android projects, which means that my configuration for the react-native development environment is correct. I don't know why it has such an error. Could you tell me how to fix that specifically?

**Comment by race604** [comment]
Please try this APK assembled by myself: http://7rf9ir.com1.z0.glb.clouddn.com/ZhiHuDaily-React-Native-1.apk

**Comment by whmsysu** [comment]
I already installed that APK successfully. But I still wonder why I can not run the code on my phone.

**Comment by race604** [comment]
This maybe help: http://stackoverflow.com/questions/29287987/invariant-violation-application-awesomeproject-has-not-been-registered-when-b . According to this, please check if other JS server is running?

**Comment by whmsysu** [comment]
The JS server is running. I can run other react native project on the phone. I don't think it's the JS server's problem.

**Comment by race604** [comment]
Open this url in your browser: http://localhost:8081/index.android.bundle?platform=android , and search for `AppRegistry.registerComponent('RCTZhiHuDaily',function(){return RCTZhiHuDaily;});`, could you find one?

**Comment by whmsysu** [comment]
I can find two "AppRegistry.registerComponent('RCTZhiHuDaily',function(){return RCTZhiHuDaily;});" on that page.

**Comment by race604** [comment]
That's the problem. You could do this, find all file named `ReactNativeDevBundle.js` and delete them. You should find them here: 

```
$ find . -name 'ReactNativeDevBundle.js'
./app/build/intermediates/assets/debug/ReactNativeDevBundle.js
./app/src/main/assets/ReactNativeDevBundle.js
```

And restart your JS server, then Reload JS, try again.

**Comment by whmsysu** [comment]
I didn't do anything but recompile the whole app, then the app doesn't  show this error message now., but it still shows other error messages. I will open other issue. Thanks, man.

**Comment by whmsysu** [comment]
I update the new npm and run the project successfully. Please close this issue. Thanks, man.
